[package]
name = "bevy_rapier_kinematics"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.13.2"
bevy_flycam = "0.13.0"
bevy_rapier3d = "0.26.0"
bevy-inspector-egui = "0.24.0"
k = "0.31.0"
bevy-trait-query = "0.5.1"

[profile.dev.package."*"]
opt-level = 3
